routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});


Route::group([
    'middleware' => [],
], function () {
    //Basic authorization
    Route::group(['middleware' => 'auth'], function () {

        Route::resource('users', \App\Http\Controllers\UserController::class);
        Route::resource('loans', \App\Http\Controllers\LoanController::class);
        Route::get('loans/{loanId}/approve', '\App\Http\Controllers\LoanController@approve');
        Route::get('loans/{loanId}/pay-now', '\App\Http\Controllers\LoanController@payInstallment');
        Route::get('loans/user/{userId}', '\App\Http\Controllers\LoanController@debtorDetails');
    });

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

});

Auth::routes();

app/Models/Loan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Loan extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'total_amount',
        'total_tenure',
        'user_id',
        'purpose',
        'frequency',
        'installment_amount',
    ];

    public function balanceAmount()
    {
        return number_format($this->total_amount - ($this->meta->count() * $this->installment_amount), 2);
    }

    public function meta()
    {
        return $this->hasMany(LoanMeta::class, 'loan_id', 'id');
    }

    public function balanceTenure()
    {
        return $this->total_tenure - $this->meta->count();
    }

    public function getApproverName()
    {
        return $this->approvedBy ? $this->approvedBy->name : '';
    }

    public function getDebtorName()
    {
        return $this->user ? $this->user->name : '';
    }

    public function user()
    {
        return $this->hasOne(User::class, 'id', 'user_id');
    }

    public function approvedBy()
    {
        return $this->hasOne(User::class, 'id', 'approved_by');
    }
}

app/Http/Controllers/LoanController.php
<?php

namespace App\Http\Controllers;

use App\Enum\Status;
use App\Http\Requests\LoanRequest;
use App\Models\Loan;
use App\Service\Contract\LoanServiceInterface;
use App\Service\Contract\UserServiceInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LoanController extends Controller
{
    protected $userService;

    protected $loanService;

    /**
     * LoanController constructor.
     * @param UserServiceInterface $userServiceInterface
     * @param LoanServiceInterface $loanServiceInterface
     */
    public function __construct(UserServiceInterface $userServiceInterface, LoanServiceInterface $loanServiceInterface)
    {
        $this->userService = $userServiceInterface;
        $this->loanService = $loanServiceInterface;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $temp = 1;
        if(Auth::user()->is_admin == Status::ADMIN) {
            $loans = $this->loanService->getDebtors();
            return view('loans.admin-listing', compact('loans', 'temp'));
        }

        $loans = $this->loanService->getByUserId(Auth::id());
        return view('loans.listing', compact('loans', 'temp'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::user()->is_admin == Status::ADMIN) {
            abort(404);
        }

        return view('loans.create');
    }

    /**
     * @param LoanRequest $request
     * @return mixed
     */
    public function store(LoanRequest $request)
    {
        if(Auth::user()->is_admin == Status::ADMIN) {
            abort(404);
        }

        $this->loanService->store(array_merge($request->except(['_token']), ['user_id' => Auth::id()]));
        return redirect('loans')->with('status', 'You have successfully requested for Loan');
    }


    public function debtorDetails(Request $request, int $userId)
    {
        $temp = 1;
        $user = $this->userService->find($userId);
        return view('loans.debtor-details', compact('user', 'temp'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Loan  $loan
     * @return \Illuminate\Http\Response
     */
    public function show(Loan $loan)
    {
        return view('loans.show', compact('loan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Loan  $loan
     * @return \Illuminate\Http\Response
     */
    public function edit(Loan $loan)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Loan  $loan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Loan $loan)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Loan  $loan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Loan $loan)
    {
        //
    }

    /**
     * @param Request $request
     * @param int $loanId
     * @return mixed
     */
    public function approve(Request $request, int $loanId)
    {
        $this->loanService->approve($loanId);
        return redirect('loans')->with('status', 'Loan has been approved!');
    }

    public function payInstallment(Request $request, int $loanId)
    {
        $this->loanService->payInstallment($loanId);
        return redirect('loans')->with('status', 'Installment amount has been paid!');
    }
}

resources/views/loans/admin-listing.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper" style="min-height: 163px; margin-left: 0px !important">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Loans</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Listing</h3>
                  @if (session('status'))
                      <div class="alert alert-success">
                          {{ session('status') }}
                      </div>
                  @endif

              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                   <div class="row">
                   </div>
                   <div class="row">
                      <div class="col-sm-12">
                         <table id="example1" class="table table-bordered table-striped dataTable dtr-inline" role="grid" aria-describedby="example1_info">
                            <thead>
                               <tr role="row">
                                   <th>Debtor Name</th>
                                   <th>Purpose</th>
                                   <th>Total Amount</th>
                                   <th>Balance Amount</th>
                                   <th>Total Tenure</th>
                                   <th>Balance Tenure</th>
                                   <th>Approved By</th>
                               </tr>
                            </thead>
                            <tbody>
                               @foreach($loans as $loan)
                                 <tr role="row" @if($temp % 2 == 0) class="even" @else class="odd" @endif>
                                     <td tabindex="0" class="sorting_1"><a href="{{url('loans/user/'.$loan->user_id)}}">{{$loan->getDebtorName()}}</a></td>
                                     <td>{{$loan->purpose}}</td>
                                     <td>$ {{$loan->total_amount ?? 0}}</td>
                                     <td>$ {{$loan->balanceAmount()}}</td>
                                     <td>{{$loan->total_tenure ?? 0}}</td>
                                     <td>{{$loan->balanceTenure()}}</td>
                                     <td>
                                        @if($loan->approved_by)
                                            {{$loan->getApproverName()}}
                                         @else
                                            <a href="{{url('loans/'.$loan->id.'/approve')}}">Approve</a>
                                         @endif
                                     </td>
                                 </tr>
                                @endforeach
                            </tbody>
                         </table>
                      </div>
                      <div class="">
                        @if($loans->count() == 0)
                          No loans found.
                        @endif
                      </div>
                   </div>
                </div>
                </div>
              </div>
                
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@endsection

resources/views/loans/create.blade.php
@extends('layouts.app')
@section('content')
   <div class="col-md-12">
      <div class="card card-warning">
         <div class="card-header">
            <h3 class="card-title">Request Loan</h3>
         </div>
         <!-- /.card-header -->
         <div class="card-body">
            @if ($errors->any())
               <div class="alert alert-danger">
                  <ul>
                     @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                     @endforeach
                  </ul>
               </div>
            @endif
            <form role="form" method="POST" name="" action="{{ route('loans.store') }}">
               {{ csrf_field() }}
               <div class="row">
                  <div class="col-sm-6">
                     <div class="form-group" id="category">
                        <label for="category">Loan Term</label>
                        <select class="form-control select2" required style="width: 100%;" tabindex="1" name="frequency">
                           <option value="Weekly">Weekly</option>
                        </select>
                     </div>
                     <div class="form-group" id="device">
                        <label for="device">Purpose</label>
                        <input type="text" class="form-control" required tabindex="2" name="purpose" id="purpose" value="{{ old('purpose') ? old('purpose') : '' }}" />
                     </div>
                     <div class="form-group">
                        <label>Amount</label>
                        <input type="number" class="form-control" required tabindex="3" name="total_amount" value="{{ old('total_amount') ? old('total_amount') : '' }}" />
                     </div>
                     <div class="form-group">
                        <label>Tenure</label>
                        <select class="form-control" name="total_tenure" id="total_tenure" required tabindex="4">
                           <option value="8">8 Weeks</option>
                           <option value="16">16 Weeks</option>
                           <option value="20">20 Weeks</option>
                           <option value="28">28 Weeks</option>
                           <option value="40">40 Weeks</option>
                        </select>
                     </div>

                     <div class="col-sm-6">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="reset" class="btn btn-default">Cancel</button>
                     </div>
                  </div>
                  <div class="col-sm-6">
                     <div class="form-group">
                     </div>
                  </div>
                  <div class="col-sm-6">
                  </div>
            </form>
         </div>
         <!-- /.card-body -->
      </div>
      <!-- /.card -->
   </div>
@endsection

resources/views/loans/debtor-details.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper" style="min-height: 163px; margin-left: 0px !important">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><a href="{{url('loans')}}"><i class="fa fa-arrow-left"></i> </a> #{{$user->id}} - {{$user->name}} </h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
              @foreach($user->loan as $loan)
                <div class="card">
                  <div class="card-header">
                    <h4 class="card-title">
                        Purpose: <b>{{$loan->purpose}}</b>
                    </h4><br/>
                      <div class="row invoice-info">
                          <div class="col-sm-4 invoice-col">
                              <address>
                                  Total Amount: <b>$ {{$loan->total_amount}}</b> <br>
                                  Total Tenure: <b>$ {{$loan->total_amount}}</b><br>
                                  Interest Rate: <b>{{$loan->interest_rate}} %</b><br>
                                  Installment Amount: <b>$ {{$loan->installment_amount}}</b>
                              </address>
                          </div>
                          <!-- /.col -->
                          <div class="col-sm-4 invoice-col">
                              <address>
                                  <strong></strong><br>
                                  Pending Amount: <b>$ {{$loan->balanceAmount()}}</b><br/>
                                  Pending Tenure: <b>{{$loan->balanceTenure()}}</b> <br/>
                              </address>
                          </div>
                          <!-- /.col -->
                          <div class="col-sm-4 invoice-col">
                              <br>
                              Approved By: <b>{{$loan->getApproverName()}}</b> <br>
                              Loan Requested On: <b>{{\Carbon\Carbon::parse($loan->created_at)->diffForHumans()}}</b> <br>
                          </div>
                          <!-- /.col -->
                      </div>
                  </div>
                  <!-- /.card-header -->
                  <div class="card-body">
                    <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                       <div class="row">
                       </div>
@if($loan->meta)
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example1" class="table table-bordered table-striped dataTable dtr-inline" role="grid" aria-describedby="example1_info">
                                    <thead>
                                    <tr role="row">
                                        <th>Tenure No</th>
                                        <th>Paid At</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @php $tenureCount=1; @endphp
                                    @foreach($loan->meta as $meta)
                                        <tr role="row">
                                            <td>#{{$tenureCount}}</td>
                                            <td>{{ $meta->paid_at ? \Carbon\Carbon::parse($meta->paid_at)->diffForhumans() : ''}}</td>
                                        </tr>
                                        @php $tenureCount++; @endphp
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <div class="">

                            </div>
                        </div>
    @endif
                  </div>

                  <!-- /.card-body -->
                </div>
                <!-- /.card -->


                <!-- /.card -->
              </div>
          @endforeach
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@endsection

resources/views/loans/listing.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper" style="min-height: 163px; margin-left: 0px !important">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Loans</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ url('/loans/create') }}">Request Loan</a></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Listing</h3>
                  @if (session('status'))
                      <div class="alert alert-success">
                          {{ session('status') }}
                      </div>
                  @endif
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                   <div class="row">
                   </div>
                   <div class="row">
                      <div class="col-sm-12">
                         <table id="example1" class="table table-bordered table-striped dataTable dtr-inline" role="grid" aria-describedby="example1_info">
                            <thead>
                               <tr role="row">
                                  <th>Purpose</th>
                                   <th>Total Amount</th>
                                   <th>Balance Amount</th>
                                   <th>Total Tenure</th>
                                   <th>Balance Tenure</th>
                                   <th>Approved By</th>
                                   <th>Approved At</th>
                               </tr>
                            </thead>
                            <tbody>
                               @foreach($loans as $loan)
                                 <tr role="row" @if($temp % 2 == 0) class="even" @else class="odd" @endif>
                                    <td tabindex="0" class="sorting_1"><a href="{{url('loans/'.$loan->id)}}">{{$loan->purpose}}</a></td>
                                     <td>$ {{$loan->total_amount ?? 0}}</td>
                                     <td>$ {{$loan->balanceAmount()}}</td>
                                     <td>{{$loan->total_tenure ?? 0}}</td>
                                     <td>{{$loan->balanceTenure()}}</td>
                                     <td>{{$loan->getApproverName()}}</td>
                                     <td>{{ $loan->approved_at ? \Carbon\Carbon::parse($loan->approved_at)->diffForhumans() : ''}}</td>
                                 </tr>
                                @endforeach
                            </tbody>
                         </table>
                      </div>
                      <div class="">
                        @if($loans->count() == 0)
                          No loans found. <a href="{{ route('loans.create') }}">Request Loan</a>
                        @endif
                      </div>
                   </div>
                </div>
                </div>
              </div>
                
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@endsection

resources/views/loans/show.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper" style="min-height: 163px; margin-left: 0px !important">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
              <h1><a href="{{url('loans')}}"><i class="fa fa-arrow-left"></i> </a> #{{$loan->id}} - {{$loan->getDebtorName()}} </h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">
                                    Purpose: <b>{{$loan->purpose}}</b>
                                </h4><br/>
                                <div class="row invoice-info">
                                    <div class="col-sm-4 invoice-col">
                                        <address>
                                            Total Amount: <b>$ {{$loan->total_amount}}</b> <br>
                                            Total Tenure: <b>$ {{$loan->total_amount}}</b><br>
                                            Interest Rate: <b>{{$loan->interest_rate}} %</b><br>
                                            Installment Amount: <b>$ {{$loan->installment_amount}}</b>
                                        </address>
                                    </div>
                                    <!-- /.col -->
                                    <div class="col-sm-4 invoice-col">
                                        <address>
                                            <strong></strong><br>
                                            Pending Amount: <b>$ {{$loan->balanceAmount()}}</b><br/>
                                            Pending Tenure: <b>{{$loan->balanceTenure()}}</b> <br/>
                                        </address>
                                    </div>
                                    <!-- /.col -->
                                    <div class="col-sm-4 invoice-col">
                                        <br>
                                        Approved By: <b>{{$loan->getApproverName()}}</b> <br>
                                        Loan Requested On: <b>{{\Carbon\Carbon::parse($loan->created_at)->diffForHumans()}}</b> <br>

                                        @if($loan->balanceTenure() && $loan->approved_by)
                                            <h4 class="pull-right"><a href="{{url('loans/'.$loan->id.'/pay-now')}}"><button class="btn btn-primary">Pay Now</button></a></h4>
                                        @endif
                                    </div>
                                    <!-- /.col -->
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                    <div class="row">
                                    </div>
                                    @if($loan->meta)
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <table id="example1" class="table table-bordered table-striped dataTable dtr-inline" role="grid" aria-describedby="example1_info">
                                                    <thead>
                                                    <tr role="row">
                                                        <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">Tenure No</th>
                                                        <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Paid At</th>
                                                    </tr>
                                                    </thead>
                                                    <tbody>
                                                    @php $tenureCount=1; @endphp
                                                    @foreach($loan->meta as $meta)
                                                        <tr role="row">
                                                            <td>#{{$tenureCount}}</td>
                                                            <td>{{ $meta->paid_at ? \Carbon\Carbon::parse($meta->paid_at)->diffForhumans() : ''}}</td>
                                                        </tr>
                                                        @php $tenureCount++; @endphp
                                                    @endforeach
                                                    </tbody>
                                                </table>
                                            </div>
                                            <div class="">

                                            </div>
                                        </div>
                                    @endif
                                </div>

                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->


                            <!-- /.card -->
                        </div>
                <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@endsection